"""add source category

Revision ID: eb30299a5775
Revises: d6cf1b84406a
Create Date: 2026-09-30 06:46:26.704388+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "eb30299a5775"
down_revision: str | Sequence[str] | None = "d6cf1b84406a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Mettre à True si cette migration supprime des données (DROP, suppression de colonne...).
# scripts/migrate.py refusera alors de l'appliquer automatiquement.
destructive = False


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sources",
        sa.Column(
            "category",
            sa.Enum(
                "jobs", "clients", "services", name="sourcecategory", native_enum=False, length=40
            ),
            server_default="jobs",
            nullable=False,
        ),
    )
    op.create_index(op.f("ix_sources_category"), "sources", ["category"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sources_category"), table_name="sources")
    op.drop_column("sources", "category")
    # ### end Alembic commands ###
