"""add auto apply

Revision ID: b3f994246232
Revises: eb30299a5775
Create Date: 2026-09-30 11:02:05.838633+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "b3f994246232"
down_revision: str | Sequence[str] | None = "eb30299a5775"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Mettre à True si cette migration supprime des données (DROP, suppression de colonne...).
# scripts/migrate.py refusera alors de l'appliquer automatiquement.
destructive = False


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auto_apply_settings",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "mode",
            sa.Enum("prepare", "send", name="autoapplymode", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("min_score", sa.Integer(), nullable=False),
        sa.Column("daily_limit", sa.Integer(), nullable=False),
        sa.Column("categories", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("countries", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("remote_only", sa.Boolean(), nullable=False),
        sa.Column("excluded_keywords", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("max_job_age_days", sa.Integer(), nullable=False),
        sa.Column("cv_document_id", sa.Uuid(), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cv_document_id"],
            ["documents.id"],
            name=op.f("fk_auto_apply_settings_cv_document_id_documents"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_auto_apply_settings_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auto_apply_settings")),
        sa.UniqueConstraint("user_id", name=op.f("uq_auto_apply_settings_user_id")),
    )
    op.add_column(
        "applications",
        sa.Column("is_automatic", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("applications", "is_automatic")
    op.drop_table("auto_apply_settings")
    # ### end Alembic commands ###
